[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[terminal.shell]
program = "/usr/bin/zsh"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 11.0
